export const bot = [
    {id: 0, response: ", it's nice to meet you. So, what do you want to get out of being here today?"},
    {id: 1, response: "Okay, and how would you define the problem that you are seeking help for?"},
    {id: 2, response: "How often does this problem affect you?"},
    {id: 3, response: "How long has it been going on?"},
    {id: 4, response: "What is said or done when this problem occurs?"},
    {id: 5, response: "What happens next?"},
    {id: 6, response: "How have you dealt with the problem so far?"},
    {id: 7, response: "Thank you for sharing with me. Next, I want to help you see solutions to your problem. Keep in mind that the solution may not resolve the problem entirely, and that's okay, because some improvement is better than no improvement or the problem getting worse. Solutions can also be a skill that you already have or something that has worked in the past. How have you already tried to address this problem?"},
    {id: 8, response: "What has worked, even a little bit?"},
    {id: 9, response: "Have there been changes for better or worse since you tried to address the problem?"},
    {id: 10, response: "Who else noticed this?"},
    {id: 11, response: "Tell me about times when the problem is not occurring or when it is not really affecting you very much."},
    {id: 12, response: "Is there something that makes the problem better at certain times?"},
    {id: 13, response: "What are you doing differently at these times?"},
    {id: 14, response: "Is this something you can try doing more of or keep doing?"},
    {id: 15, response: "Now tell me about a time when the problem did not occur at all. What was different that the problem did not occur? What were you doing that was different?"},
    {id: 16, response: "Is this something you can try doing again?"},
    {id: 17, response: "On a scale from 0–10 with 10 being the best, tell me how you felt when things were at  their worst."},
    {id: 18, response: "Where are you on that scale right now?"},
    {id: 19, response: "A 10 may be too big a goal at the moment. What number will be acceptable for you?"},
    {id: 20, response: "How will you recognize when you are one point further up the scale?"},
    {id: 21, response: "What else will be different when you are one point further up?"},
    {id: 22, response: "Who will notice?"},
    {id: 23, response: "How do you keep from being at a lower number?"},
    {id: 24, response: "How have you managed to keep things from getting worse?"},
    {id: 25, response: "What else helps?"},
    {id: 26, response: "Now, I'm going to ask you a question that requires some imagination. Suppose you go to sleep tonight and while you are asleep a miracle happens and the problem that brought you here is solved. But you were asleep and don’t know that it has been solved. How will you discover that this miracle happened? What will be the first things you notice are different that will tell you that this miracle has happened and that the problem has been solved?"},
    {id: 27, response: "Who will notice first and what will they notice about you that will indicate that things are better? What will they notice you doing differently?"},
    {id: 28, response: "What will it be like when the problem is solved? What will be different?"},
    {id: 29, response: "What will you be doing instead?"},
    {id: 30, response: "What difference will it make?"},
    {id: 31, response: "The miracle question helps you see what you would rather be doing instead of dealing with the problem. This is the future you prefer and are working towards. During this session, you did a great job identifying some potential solutions as well as some strengths and coping skills that you already have, some that have already worked in the past and can be used again. You already have the skills you need to bring positive change to your life, now its time for you to apply these solutions to get to your preferred future. If you are not seeing any progress and would like to find other solutions, or have another problem you would like to find a solution for, feel free to chat with me again!"}
];
