export const bot = [
    {id: 0, response: ", it's nice to meet you. So, what problem brings you here today?"},
    {id: 1, response: "Okay, and how would you define your problem?"},
    {id: 2, response: "How often does this problem occur?"},
    {id: 3, response: "How long has this problem been occurring?"},
    {id: 4, response: "What happens when this problem occurs? What is said or done and by whom?"},
    {id: 5, response: "What happens after?"},
    {id: 6, response: "How have you coped or dealt with the problem so far?"},
    {id: 7, response: "Thank you for sharing with me. Next, I want to help you see solutions to your problem. Keep in mind that the solution may not resolve the problem entirely, and that's okay, because some improvement is better than no improvement or the problem getting worse. Solutions can also be a skill that you already have or something that has worked in the past. How have you already tried to address this problem?"},
    {id: 8, response: "What has worked even a little?"},
    {id: 9, response: "What changes have happened since you tried to address this problem? Did it get better or worse?"},
    {id: 10, response: "When is the problem not occurring or not affecting you as much?"},
    {id: 11, response: "Is there something that makes the problem better sometimes?"},
    {id: 12, response: "What are you doing that is different?"},
    {id: 13, response: "Is this something you can try doing more of or keep doing?"},
    {id: 14, response: "Now tell me about a time when the problem did not occur at all. What was different about that time and what were you doing that was different?"},
    {id: 15, response: "Is this something you can try doing again?"},
    {id: 16, response: "On a scale from 0–10, with 10 being the best in terms of the problem, and 0 being how you felt when the problem was at its worst, where would you place yourself on the scale right now?"},
    {id: 17, response: "10 may not be a realistic goal at the moment, so what number will be an acceptable goal for you?"},
    {id: 18, response: "How will you know when you are one point further up the scale?"},
    {id: 19, response: "What other differences will there be when you are one point further up?"},
    {id: 20, response: "Who else will notice this?"},
    {id: 21, response: "How do you keep from being at a lower number?"},
    {id: 22, response: "How have you managed to keep things from getting worse?"},
    {id: 23, response: "What else helps?"},
    {id: 24, response: "Now, I'm going to ask you a question that requires some imagination. Suppose you go to sleep tonight and while you are asleep a miracle happens and the problem that brought you here is solved. But you were asleep and don’t know that it has been solved. How will you discover that this miracle happened? What will be the first signs you notice are different that will tell you that this miracle has happened and that the problem has been solved?"},
    {id: 25, response: "Who else will notice?"},
    {id: 26, response: "What will they notice about you or you doing differently when this happens?"},
    {id: 27, response: "What will it be like when the problem is solved? What will be different?"},
    {id: 28, response: "What will you be doing instead?"},
    {id: 29, response: "What difference will it make?"},
    {id: 30, response: "The miracle question helps you see what you would rather be doing instead of dealing with the problem. This is the future you prefer and are working towards. During this session, you did a great job identifying some potential solutions as well as some strengths and coping skills that you already have, some that have already worked in the past and can be used again. You already have the skills you need to bring positive change to your life, now its time for you to apply these solutions to get to your preferred future. If you are not seeing any progress and would like to find other solutions, or have another problem you would like to find a solution for, feel free to chat with me again!"}
];
