export const bot = [
    {id: 0, response: ", it's nice to meet you. So, what do you want to get out of being here today?"},
    {id: 1, response: "Okay, and how would you define the problem that you are seeking help for?"},
    {id: 2, response: "How often does this problem affect you?"},
    {id: 3, response: "How long has it been going on?"},
    {id: 4, response: "What is said or done when this problem occurs?"}/*,
    {id: 5, response: "What happens next?"},
    {id: 6, response: "How have you dealt with it in the past?"},
    {id: 7, response: "How have you already tried to address this problem?"},
    {id: 8, response: "Thank you for sharing with me. Next, I want to help you see solutions to your problem. Now keep in mind that the solution may not resolve the problem entirely, and that's okay, because some improvement is better than no improvement or the problem getting worse. Sometimes solutions can be a skill that you already have or something that has worked in the past."},
    {id: 9, response: "How have you tried to address this problem?"},
    {id: 10, response: "What has worked, even a little bit?"},
    {id: 11, response: "Have there been changes for better or worse since you decided to take action?"},
    {id: 12, response: "Who else noticed this?"},
    {id: 13, response: "What will it be like when the problem is solved?"},
    {id: 14, response: "What will you be doing instead?"},
    {id: 15, response: "When that happens, what difference will it make?"},
    {id: 16, response: "How will other people know that things are better?"},
    {id: 17, response: "Who will notice?"},
    {id: 18, response: "What else will be different?"},
    {id: 19, response: "Tell me about times when the problem is not occurring or when it is not really affecting  you very much."},
    {id: 20, response: "Is there something that makes the problem better at certain times?"},
    {id: 21, response: "What are you doing differently at these times?"},
    {id: 22, response: "What else is better at these times?"},
    {id: 23, response: "On a scale from 0–10 with 10 being the best, tell me how you felt when things were at  their worst."},
    {id: 24, response: "Where are you on that scale right now?"},
    {id: 25, response: "Tell me what was going on with you when you felt like a 10."},
    {id: 26, response: "Therapy can help you with your problem, but maybe a “10” is too big a goal. What number will be acceptable for you?"},
    {id: 27, response: "How will you recognize when you are one point further up the scale?"},
    {id: 28, response: "What else will be different when you are one point further up?"},
    {id: 29, response: "Who will notice?"},
    {id: 30, response: "How will you get through the rest of today?"},
    {id: 31, response: "How have you kept going so far?"},
    {id: 32, response: "What else helps?"},
    {id: 33, response: "Is there anyone else who helps you with this problem?"},
    {id: 34, response: "How do these people help you with the problem?"},
    {id: 35, response: "I’m going to ask you a kind of strange question now. Suppose you go to sleep tonight as  usual and while you are asleep a miracle happens and the problem that brought you  here today is solved. But you are asleep and don’t know that it has been solved. What  will be the first small signs that this miracle has happened, and that the problem has been solved?"}*/
];
